### ISSUE TITLE
Example linked in readme has been deleted

### ISSUE THREAD

**Issue by elssar** [ORESoftware/suman#1]
The example blog post listed in the readme (https://medium.com/@the1mills/introducing-suman-a-node-js-testing-library-20fdae524cd) has been deleted and returns a 410.

**Comment by ORESoftware** [comment]
@elssar thanks for the comment - actually I never meant to post that Medium post :) it was a draft and I accidentally hit the 'publish' button, I tried to delete it but it remained in cyberspace. Suman is in beta. It works really well, and makes huge improvements on Mocha and will compete with Ava, but there's not much documentation yet. I can let you know when it's ready. It's going really well, TBH.
