### ISSUE TITLE
You may to try `function-arguments` instead of using `parse-function`

### ISSUE THREAD

**Issue by tunnckoCore** [ORESoftware/suman#2]
Hi!
I've just created http://npm.im/function-arguments that also supports ES2015 - generator functions, regular functions and arrow functions. And because i review you project I seen that you just use `.args` property from `parse-function`, so you can replace it with the other package.
This will also give performance bump, because not using `acorn`. And really acorn is not needed for arguments - http://npm.im/orientjs and http://npm.im/karma-server-side are good example when you need `parse-function`.

**Comment by ORESoftware** [comment]
Cool thanks, I will take note!

**Comment by ORESoftware** [comment]
I need to parse arguments for generator functions, so your new lib will come in handy, thanks again

**Comment by ORESoftware** [comment]
been using your lib with great success thanks!
