### ISSUE TITLE
Suman uncaught exception: Cannot find module 'suman-utils/utils'

### ISSUE THREAD

**Issue by samzilverberg** [ORESoftware/suman#3]
Hey there, 
I really like the idea behind the lib. 
I decided to try and convert our current mocha tests to suman but immediately ran into error using suman.

```
mkdir bla
cd bla
npm install -g suman
suman --init

 => Suman uncaught exception =>
 Error: Cannot find module 'suman-utils/utils'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/____/.nvm/versions/node/v4.4.5/lib/node_modules/suman/lib/utils.js:1:80)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
```

i'm using nvm and i tried on both node v4.4.5 and v6.2.2

**Comment by samzilverberg** [comment]
installing suman so works:
```
npm i -g https://github.com/ORESoftware/suman
```
`suman --init` works without error.

so npm has an older broken version of suman, please republish as 0.0.2

**Comment by the1mills** [comment]
thanks for opening an issue, I know what problem you are running into, let me fix it, will get back to your shortly

**Comment by the1mills** [comment]
were you able to convert your mocha test suites with Github version of this project?

**Comment by ORESoftware** [comment]
this project is dormant, and still in Beta, I will ping you on this thread when I smooth out things enough to experiment

**Comment by ORESoftware** [comment]
you can try it now if you want, install suman@1.1.42

**Comment by samzilverberg** [comment]
hi there, sorry but didnt have time to try it yet.

**Comment by the1mills** [comment]
np, let me know if need help getting it to work, --convert option works well. But if you have shared global variables in your test suites then you have to get rid of them. You can put those in suman.globals.js if you must use globals.

**Comment by ORESoftware** [comment]
resolved for now, let me know if you have a similar issue!

**Comment by samzilverberg** [comment]
👍 thanks, still didnt get to trying it :(
hope to be able to in the coming month

**Comment by the1mills** [comment]
Np, I am improving the docs all the time so better to wait anyway,
expecting official release before Christmas
